In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import minimize


In [2]:
def beacons():
    
    # beacon locations
    b1 = [0.,0.]
    b2 = [0., 0.820]
    b3 = [1.12, 0.820]
    b4 = [1.12, 0.]
    
    return [b1, b2, b3, b4]

In [21]:
def error(position,distanceEstimate):
    
    x = position[0]
    y = position[1]
    d = distanceEstimate
    b = beacons()
    
    err = 0.0
    
    for i in range(len(d)):
        err +=  (np.sqrt((b[i][0]- x)**2 + (b[i][1]- y)**2) - d[i])**2
    
    return err


In [22]:
b = beacons()
bnds = ((0.,b[3][0]),tuple(b[1]))
bnds


((0.0, 1.12), (0.0, 0.82))

In [23]:
# Parce Data
data = pd.read_csv('test02.txt', sep=",", header=None)
data = np.array(data)
print(data)

[[ 0.16189765  1.59814603  0.31890656  0.33071271]
 [ 0.1453557   0.80711775  0.31890656  0.27645305]
 [ 0.36787944  1.07404143  0.1453557   0.27645305]
 [ 0.15611805  1.07404143  0.31890656  0.26692409]
 [ 0.16189765  0.50766484  0.1453557   0.25739514]
 [ 0.16767725  0.54525307  0.1934266   0.27645305]
 [ 0.15073687  0.83699782  0.1453557   0.27645305]
 [ 0.15611805  0.93106278  0.1453557   0.29692203]
 [ 0.16767725  0.72557492  0.1453557   0.25739514]
 [ 0.15611805  0.75147729  0.1453557   0.27645305]
 [ 0.27645305  0.48954166  0.1453557   0.46394605]
 [ 0.42437285  0.6531016   0.1453557   0.53377599]
 [ 0.1453557   0.80711775  0.1453557   0.27645305]
 [ 0.15611805  0.8668779   0.1453557   0.46394605]
 [ 0.16189765  0.87573865  0.1453557   0.29692203]
 [ 0.16189765  0.54525307  0.1453557   0.29692203]
 [ 0.15611805  0.69967254  0.1453557   0.25739514]
 [ 0.1453557   0.75147729  0.15073687  0.56471812]
 [ 0.15611805  1.11380321  0.23213113  0.25739514]
 [ 0.42437285  0.80711775  0.14

In [29]:
distEst = data[1]
print(distEst)
b = beacons()
positionInitial = [0.45, 0.55]
len(distEst)
distEst[0]

[ 0.1453557   0.80711775  0.31890656  0.27645305]


0.14535570123384661

In [30]:
sol = minimize(error,positionInitial,args=(distEst),method='CG',options={'gtol': 1e-6, 'disp': True})
sol

Optimization terminated successfully.
         Current function value: 0.546965
         Iterations: 6
         Function evaluations: 52
         Gradient evaluations: 13


     fun: 0.5469651634471069
     jac: array([  3.72529030e-08,   2.98023224e-08])
 message: 'Optimization terminated successfully.'
    nfev: 52
     nit: 6
    njev: 13
  status: 0
 success: True
       x: array([ 0.63149462,  0.26347138])