# Compute the Varience for each of the Beacons
### To be used for the weighted circular algorithm for localization

In [1]:
# import libraries
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('varCalcData.txt', sep=",", header=None)
data = np.array(data)
print(data)

[[ 0.34251886  0.75147729  0.39511776  1.07404143]
 [ 0.42437285  0.75147729  0.75915848  0.42437285]
 [ 0.48954166  0.96553139  0.54803616  0.3814986 ]
 [ 0.56471812  0.56615934  0.31890656  0.29692203]
 [ 0.52578802  0.69967254  0.31890656  0.30791429]
 [ 0.62898486  0.69967254  0.56615934  0.49454548]
 [ 1.2389766   0.75147729  0.65143906  0.42437285]
 [ 0.74789045  1.06891497  0.45579402  0.47266784]
 [ 0.56471812  0.89897034  0.48954166  0.39511776]
 [ 1.15356499  0.93106278  0.75147729  0.49454548]
 [ 0.8668779   0.66133596  0.93106278  0.80711775]
 [ 1.42924003  0.97045967  0.80711775  0.80711775]
 [ 1.          0.8668779   0.48954166  0.80711775]
 [ 1.07404143  0.75147729  0.80711775  0.69967254]
 [ 1.3307122   0.8091776   0.54525307  0.52578802]
 [ 0.36787944  0.45579402  0.86909026  0.80711775]
 [ 0.80711775  1.          0.8091776   0.93106278]
 [ 0.69967254  0.84983627  0.8668779   0.65143906]
 [ 1.42924003  0.50766484  0.67900398  0.65143906]
 [ 0.66133596  1.          0.48

In [6]:
var_d = np.var(data, dtype=np.float64, axis=0)
print(var_d)

[ 0.11927523  0.02750445  0.03445816  0.04617075]
