# Compute the Varience for each of the Beacons
### To be used for the weighted circular algorithm for localization

In [2]:
# import libraries
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('varCalcData.txt', sep=",", header=None)
data = np.array(data)
print(data)

[[ 0.65143906  0.27645305  0.48954166  0.34251886]
 [ 0.46271861  0.56471812  0.48954166  0.34251886]
 [ 0.83699782  0.26692409  0.6755558   0.31890656]
 [ 0.69967254  0.27645305  0.48954166  0.31890656]
 [ 0.69967254  0.27645305  0.48954166  0.34251886]
 [ 0.93106278  0.27645305  0.48954166  0.41183673]
 [ 0.47452476  0.27645305  0.69967254  0.34251886]
 [ 0.6755558   0.6531016   0.57329753  0.34251886]
 [ 0.65143906  0.27645305  0.75339514  0.33071271]
 [ 0.65143906  0.27645305  0.48954166  0.5748183 ]
 [ 0.78327522  0.27645305  0.48954166  0.31890656]
 [ 0.60653066  0.27645305  0.65143906  0.8668779 ]
 [ 0.60469838  0.27645305  0.42437285  0.33071271]
 [ 0.65143906  0.27645305  0.44232971  0.34251886]
 [ 0.81536766  0.27645305  0.39511776  0.34251886]
 [ 0.65143906  0.27645305  0.45579402  0.34251886]
 [ 0.60653066  0.27645305  0.48954166  0.34251886]
 [ 0.65143906  0.27645305  0.52578802  0.34251886]
 [ 0.65143906  0.28668754  0.39511776  0.5210957 ]
 [ 0.93106278  0.27645305  0.48

In [4]:
var_d = np.var(data, dtype=np.float64, axis=0)
print(var_d)

[ 0.01458598  0.0101502   0.00949717  0.01719393]


#### Use results here for BLE localization

In [5]:
var_d

array([ 0.01458598,  0.0101502 ,  0.00949717,  0.01719393])

In [7]:
test = var_d > 0.01

In [8]:
test

array([ True,  True, False,  True], dtype=bool)

In [10]:
np.sum(test)

3

test2 = var_d<0.01


In [15]:
test2 = var_d<0.009

In [16]:
test2

array([False, False, False, False], dtype=bool)

In [17]:
np.any(test2)

False

In [20]:
for io in range(1,4):
    print(io)

    

1
2
3
