# Compute the Varience for each of the Beacons
### To be used for the weighted circular algorithm for localization

In [1]:
# import libraries
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('varCalcData.txt', sep=",", header=None)
data = np.array(data)
print(data)

[[ 0.65143906  0.83699782  0.65143906  0.52327841]
 [ 0.75147729  0.96553139  0.58792507  0.50965925]
 [ 0.75147729  1.15356499  0.65143906  0.6755558 ]
 [ 0.72557492  0.96553139  0.75147729  0.60653066]
 [ 0.65143906  0.84983627  0.31890656  0.93106278]
 [ 0.62898486  0.93106278  0.31890656  0.34251886]
 [ 0.75147729  0.8668779   0.50928955  0.75147729]
 [ 0.69967254  1.2389766   0.31890656  0.35519915]
 [ 0.69967254  1.68671963  0.75147729  0.69967254]
 [ 0.69967254  1.42924003  0.31890656  0.93106278]
 [ 0.93106278  1.64872127  0.34251886  0.42437285]
 [ 0.60653066  1.64872127  0.31890656  0.36787944]
 [ 1.3307122   0.75147729  0.31890656  0.39511776]
 [ 1.42924003  1.3307122   0.31890656  0.54525307]
 [ 1.          1.11380321  0.31890656  0.45579402]
 [ 1.3307122   0.94057959  0.34251886  0.52578802]
 [ 0.65143906  1.          0.5210957   0.93106278]
 [ 1.48215152  1.37997611  0.55967837  0.93106278]
 [ 0.93106278  1.53506301  0.31890656  0.56471812]
 [ 0.65143906  1.90190714  0.38

In [3]:
var_d = np.var(data, dtype=np.float64, axis=0)
print(var_d)

[ 0.08024316  0.11061203  0.02423527  0.04135387]


#### Use results here for BLE localization