## Minimization using Scipy

In [1]:
# import libraries
import numpy as np
import pandas as pd
from scipy.optimize import minimize

In [2]:
def beacons():
    
    # beacon locations
    b1 = [0.,0.]
    b2 = [0., 0.820]
    b3 = [1.12, 0.820]
    b4 = [1.12, 0.]
    
    return [b1, b2, b3, b4]

Cost or objective function to be used for miniimization. This is the error of distance values.

In [3]:
def error(position,distanceEstimate):
    
    x = position[0]
    y = position[1]
    d = distanceEstimate
    b = beacons()
    
    err = 0.0
    
    for i in range(len(d)):
        err +=  (np.sqrt((b[i][0]- x)**2 + (b[i][1]- y)**2) - d[i])**2
    
    return err

Use offline data for testing.

In [4]:
# Parce Data
data = pd.read_csv('varCalcData.txt', sep=",", header=None)
data = np.array(data)
print(data)

[[ 0.65143906  0.27645305  0.48954166  0.34251886]
 [ 0.46271861  0.56471812  0.48954166  0.34251886]
 [ 0.83699782  0.26692409  0.6755558   0.31890656]
 [ 0.69967254  0.27645305  0.48954166  0.31890656]
 [ 0.69967254  0.27645305  0.48954166  0.34251886]
 [ 0.93106278  0.27645305  0.48954166  0.41183673]
 [ 0.47452476  0.27645305  0.69967254  0.34251886]
 [ 0.6755558   0.6531016   0.57329753  0.34251886]
 [ 0.65143906  0.27645305  0.75339514  0.33071271]
 [ 0.65143906  0.27645305  0.48954166  0.5748183 ]
 [ 0.78327522  0.27645305  0.48954166  0.31890656]
 [ 0.60653066  0.27645305  0.65143906  0.8668779 ]
 [ 0.60469838  0.27645305  0.42437285  0.33071271]
 [ 0.65143906  0.27645305  0.44232971  0.34251886]
 [ 0.81536766  0.27645305  0.39511776  0.34251886]
 [ 0.65143906  0.27645305  0.45579402  0.34251886]
 [ 0.60653066  0.27645305  0.48954166  0.34251886]
 [ 0.65143906  0.27645305  0.52578802  0.34251886]
 [ 0.65143906  0.28668754  0.39511776  0.5210957 ]
 [ 0.93106278  0.27645305  0.48

Want to make sure the dimensions of everything is correct for the minimization in scipy.

In [11]:
distEst = data[15]
distEst = np.reshape(distEst,(len(distEst),1))
print(distEst)

positionInitial = np.array([0.45, 0.55])
positionInitial = np.reshape(positionInitial,(len(positionInitial),1))
print(positionInitial)

b = beacons()

[[ 0.65143906]
 [ 0.27645305]
 [ 0.45579402]
 [ 0.34251886]]
[[ 0.45]
 [ 0.55]]


In [12]:
sol = minimize(error,positionInitial,args=(distEst),method='CG',options={'gtol': 1e-6, 'disp': True})
print(sol)

Optimization terminated successfully.
         Current function value: 0.344304
         Iterations: 4
         Function evaluations: 36
         Gradient evaluations: 9
     fun: 0.3443038600564301
     jac: array([ -8.79168510e-07,   2.19792128e-07])
 message: 'Optimization terminated successfully.'
    nfev: 36
     nit: 4
    njev: 9
  status: 0
 success: True
       x: array([ 0.58693524,  0.47081528])
