# Compute the Varience for each of the Beacons
### To be used for the weighted circular algorithm for localization

In [2]:
# import libraries
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('varCalcData2.txt', sep=",", header=None)
data = np.array(data)
print(data)

[[ 0.48954166  0.60653066  0.1934266   0.34251886]
 [ 0.42437285  0.60653066  0.34864492  0.34251886]
 [ 0.48954166  0.60653066  0.48954166  0.33071271]
 [ 0.48954166  0.60653066  0.52578802  0.34251886]
 [ 0.48954166  0.60653066  0.1934266   0.34251886]
 [ 0.6483297   0.60653066  0.35960731  0.31890656]
 [ 0.48954166  0.52578802  0.1934266   0.75147729]
 [ 0.45579402  0.60653066  0.18009231  0.34251886]
 [ 0.48954166  0.60653066  0.18675946  0.34251886]
 [ 0.48954166  0.80711775  0.1934266   0.34251886]
 [ 0.47266784  0.58562439  0.1934266   0.34251886]
 [ 0.42437285  0.60653066  0.1934266   0.34251886]
 [ 0.48954166  0.56471812  0.1934266   0.75147729]
 [ 0.50766484  0.56471812  0.1934266   0.34251886]
 [ 0.48954166  0.60653066  0.1934266   0.34251886]
 [ 0.45579402  0.75147729  0.25739514  0.34251886]
 [ 0.7068242   0.56471812  0.1934266   0.34251886]
 [ 0.47266784  0.60653066  0.1934266   0.69967254]
 [ 0.8668779   0.60653066  0.1934266   0.34251886]
 [ 0.48954166  0.80711775  0.19

In [4]:
var_d = np.var(data, dtype=np.float64, axis=0)
print(var_d)

[ 0.01059502  0.0054296   0.01023925  0.01989047]


#### Use results here for BLE localization

In [5]:
var_d

array([ 0.01458598,  0.0101502 ,  0.00949717,  0.01719393])

In [7]:
test = var_d > 0.01

In [8]:
test

array([ True,  True, False,  True], dtype=bool)

In [10]:
np.sum(test)

3

test2 = var_d<0.01


In [15]:
test2 = var_d<0.009

In [16]:
test2

array([False, False, False, False], dtype=bool)

In [17]:
np.any(test2)

False

In [20]:
for io in range(1,4):
    print(io)

    

1
2
3
